### PR TITLE
initialize v1.8.0

### PR DESCRIPTION
**Pull request by fonsecadeline**
No to have to generate this modification on every of our CHANGELOGs.

### CODE REVIEW

**Comment by senhalil** [comment]
I saw this test breaking randomly multiple times. It is of course not related to this PR but do you have any idea @fonsecadeline ? It is an output_test.

```
ERROR["test_returned_ids", #<Minitest::Reporters::Suite:0x000055709a7241c8 @name="Api::V01::OutputTest">, 18.742398633999983]
 test_returned_ids#Api::V01::OutputTest (18.74s)
Minitest::UnexpectedError:         TypeError: no implicit conversion of Api::V01::VrpResult into String
            /srv/app/vendor/bundle/ruby/2.5.0/bundler/gems/rack-a23188bb3297/lib/rack/mock.rb:216:in `block in body'
            /srv/app/vendor/bundle/ruby/2.5.0/bundler/gems/rack-a23188bb3297/lib/rack/mock.rb:215:in `each'
            /srv/app/vendor/bundle/ruby/2.5.0/bundler/gems/rack-a23188bb3297/lib/rack/mock.rb:215:in `body'
            /srv/app/test/api/v01/request_helper.rb:46:in `block in wait_status_csv'
            /srv/app/test/api/v01/request_helper.rb:43:in `loop'
            /srv/app/test/api/v01/request_helper.rb:43:in `wait_status_csv'
            /srv/app/test/api/v01/output_test.rb:292:in `block in test_returned_ids'
            /srv/app/test/api/v01/request_helper.rb:129:in `asynchronously'
            /srv/app/test/api/v01/output_test.rb:275:in `test_returned_ids'
```

**Comment by fonsecadeline** [comment]
> I saw this test breaking randomly multiple times. It is of course not related to this PR but do you have any idea @fonsecadeline ? It is an output_test.
> 
> ```
> ERROR["test_returned_ids", #<Minitest::Reporters::Suite:0x000055709a7241c8 @name="Api::V01::OutputTest">, 18.742398633999983]
>  test_returned_ids#Api::V01::OutputTest (18.74s)
> Minitest::UnexpectedError:         TypeError: no implicit conversion of Api::V01::VrpResult into String
>             /srv/app/vendor/bundle/ruby/2.5.0/bundler/gems/rack-a23188bb3297/lib/rack/mock.rb:216:in `block in body'
>             /srv/app/vendor/bundle/ruby/2.5.0/bundler/gems/rack-a23188bb3297/lib/rack/mock.rb:215:in `each'
>             /srv/app/vendor/bundle/ruby/2.5.0/bundler/gems/rack-a23188bb3297/lib/rack/mock.rb:215:in `body'
>             /srv/app/test/api/v01/request_helper.rb:46:in `block in wait_status_csv'
>             /srv/app/test/api/v01/request_helper.rb:43:in `loop'
>             /srv/app/test/api/v01/request_helper.rb:43:in `wait_status_csv'
>             /srv/app/test/api/v01/output_test.rb:292:in `block in test_returned_ids'
>             /srv/app/test/api/v01/request_helper.rb:129:in `asynchronously'
>             /srv/app/test/api/v01/output_test.rb:275:in `test_returned_ids'
> ```

I have no idea ... I used to see this but it had not happen to me a long time ago until now.

**Comment by senhalil** [comment]
> I have no idea ... I used to see this but it had not happen to me a long time ago until now.

If it is happening less often, it might be related to async worker logic :( even after all those fixes :facepalm: but at least it doesn't happens as often as the other broken tests. We will look into it when we have time I guess.

**Comment by fonsecadeline** [comment]
- [ ] edit date of 1.7.1 release

**Review by braktar — CHANGES_REQUESTED** [review]
Could you remove the unused categories from v1.7.1 ?

**Review by braktar — APPROVED** [review]

**Pull request merged**
