### PR TITLE
Update gems & silence test warnings

### PR DESCRIPTION
**Pull request by braktar**

### CODE REVIEW

**Review by senhalil — APPROVED** [review]
It looks good to me. What were the warnings by the way? Can you copy/paste some warning output so that we have an idea as well.

**Review by fonsecadeline — APPROVED** [review]

**Comment by alain-andre** [comment]
> It looks good to me. What were the warnings by the way? Can you copy/paste some warning output so that we have an idea as well.

It's due to gem that we own and are too old : `Mapotempo/active_hash` and `Mapotempo/balanced_vrp_clustering`

**Comment by braktar** [comment]
Some could be usefull
`/home/gwenael/projects/optimizer-api/wrappers/ortools.rb:732: warning: instance variable @killed not initialized`

But most of them come from dependencies and overwhelm the logs
```
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
/home/gwenael/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/bundler/gems/active_hash-6471576562e2/lib/active_hash/relation.rb:106: warning: instance variable @records not initialized
```

**Comment by senhalil** [comment]
Is there a setting to have only the warnings of the current project?

> Some could be usefull
> `/home/gwenael/projects/optimizer-api/wrappers/ortools.rb:732: warning: instance variable @killed not initialized`
> 

I am not even sure if we still use that variable or not :)

**Pull request closed without merging**
